services:
    content_blocks.create_content_block_handler:
        class: Backend\Modules\ContentBlocks\Command\CreateContentBlockHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "@contant_blocks.content_block_repository"
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\Command\CreateContentBlock }

    content_blocks.update_content_block_handler:
        class: Backend\Modules\ContentBlocks\Command\UpdateContentBlockHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\Command\UpdateContentBlock }

    content_blocks.delete_content_block_handler:
        class: Backend\Modules\ContentBlocks\Command\DeleteContentBlockHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "@contant_blocks.content_block_repository"
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\Command\DeleteContentBlock }

    content_blocks.copy_content_blocks_to_other_locale_handler:
        class: Backend\Modules\ContentBlocks\Command\CopyContentBlocksToOtherLocaleHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@contant_blocks.content_block_repository"
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\Command\CopyContentBlocksToOtherLocale }
