services:
    content_blocks.create_content_block_command_handler:
        class: Backend\Modules\ContentBlocks\Command\CreateContentBlockCommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\Command\CreateContentBlock }

    content_blocks.update_content_block_command_handler:
        class: Backend\Modules\ContentBlocks\Command\UpdateContentBlockCommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\Command\UpdateContentBlock }

    content_blocks.delete_content_block_command_handler:
        class: Backend\Modules\ContentBlocks\Command\DeleteContentBlockCommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\Command\DeleteContentBlock }
