services:
    contant_blocks.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\ContentBlocks\ContentBlock\ContentBlockRepository

    content_blocks.create_content_block_command_handler:
        class: Backend\Modules\ContentBlocks\ContentBlock\CreateContentBlockCommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\ContentBlock\CreateContentBlock }
