services:
    contant_blocks.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\ContentBlocks\ContentBlock\ContentBlockRepository

    content_blocks.create_content_block_command_handler:
        class: Backend\Modules\ContentBlocks\ContentBlock\Command\CreateContentBlockCommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\ContentBlock\Command\CreateContentBlock }

    content_blocks.update_content_block_command_handler:
        class: Backend\Modules\ContentBlocks\ContentBlock\Command\UpdateContentBlockCommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\ContentBlock\Command\UpdateContentBlock }

    content_blocks.delete_content_block_command_handler:
        class: Backend\Modules\ContentBlocks\ContentBlock\Command\DeleteContentBlockCommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\ContentBlock\Command\DeleteContentBlock }
