services:
  forkcms.console.cache.clear:
    class: Console\Core\CacheClearCommand
    tags:
      - { name: console.command }
  forkcms.console.thumbnails.generate:
    class: Console\Thumbnails\GenerateThumbnailsCommand
    arguments:
      - "@forkcms.utility.thumbnails"
    tags:
      - { name: console.command }
