parameters:
    database_driver:        mysql
    database_host:          localhost
    database_port:          3306
    database_name:          ~
    database_user:          root
    database_password:      ~

    #fork_debug:             %kernel_debug%
    #fork_debug_email:       ''
    #fork_debug_message:     'Internal error.'
    #fork_version:           '3.4.3'
    #fork_charset:           'utf-8'

    #site_default_title:     'Fork CMS'
    #site_multilanguage:     true

    #action_group_tag:       '@actiongroup'
    #action_rights_level:    7
