backend:
    path: /private/{_locale}/{module}/{action}
    defaults:
        _controller: ApplicationRouting::backendController
        _locale:     ~
        module:      ~
        action:      ~
backend_ajax:
    path: /backend/ajax
    defaults:
        _controller: ApplicationRouting::backendAjaxController
backend_cronjob:
    path: /backend/cronjob
    defaults:
        _controller: ApplicationRouting::backendCronjobController
frontend_ajax:
    path: /frontend/ajax
    defaults:
        _controller: ApplicationRouting::frontendAjaxController
frontend:
    path: /{route}
    defaults:
        _controller: ApplicationRouting::frontendController
        route:       ~
    requirements:
        route: (.*)
