services:
    blog.repository.comment:
        class: Backend\Modules\Blog\Domain\Comment\CommentRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Blog\Domain\Comment\Comment
