services:
    location.handler.copy_widgets_to_other_locale:
        class: Backend\Modules\Location\Command\CopyLocationWidgetsToOtherLocaleHandler
        tags:
            - { name: command_handler, handles: Backend\Modules\Location\Command\CopyLocationWidgetsToOtherLocale }
