services:
  location.repository.location:
    class: Backend\Modules\Location\Domain\Location\LocationRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - Backend\Modules\Location\Domain\Location\Location
