services:
    media_library.console.delete_media_items:
        class: Backend\Modules\MediaLibrary\Console\DeleteMediaItemsCommand
        tags:
            -  { name: console.command }

    media_library.console.delete_generated_folder:
        class: Backend\Modules\MediaLibrary\Console\DeleteFrontendFolderCommand
        tags:
            -  { name: console.command }
