services:
    media_library.manager.extension:
        class: Backend\Modules\MediaLibrary\Manager\ExtensionManager
        arguments:
            - "%media_library.image_extensions%"
            - "%media_library.file_extensions%"
            - "%media_library.movie_extensions%"
            - "%media_library.audio_extensions%"
    media_library.manager.file:
        class: Backend\Modules\MediaLibrary\Manager\FileManager
        arguments:
            - "@fork.settings"
    media_library.manager.mime_type:
        class: Backend\Modules\MediaLibrary\Manager\MimeTypeManager
        arguments:
            - "%media_library.image_mime_types%"
            - "%media_library.file_mime_types%"
            - "%media_library.movie_mime_types%"
            - "%media_library.audio_mime_types%"
    media_library.manager.storage:
        class: Backend\Modules\MediaLibrary\Manager\StorageManager
    media_library.manager.tree:
        class: Backend\Modules\MediaLibrary\Manager\TreeManager
        arguments:
            - "@media_library.cache_builder"
