services:
    media_library.manager.file:
        class: Backend\Modules\MediaLibrary\Manager\FileManager
        arguments:
            - "@fork.settings"
    media_library.manager.storage:
        class: Backend\Modules\MediaLibrary\Manager\StorageManager
        arguments:
            - "@media_library.storage.local"
            - "@media_library.storage.youtube"
            - "@media_library.storage.vimeo"
    media_library.manager.tree:
        class: Backend\Modules\MediaLibrary\Manager\TreeManager
        arguments:
            - "@media_library.cache_builder"
