imports:
  - { resource: repositories.yml }
  - { resource: commands.yml }
  - { resource: cache_builder.yml }
  - { resource: events.yml }
  - { resource: storage_providers.yml }
  - { resource: managers.yml }
  - { resource: helpers.yml }
  - { resource: console.yml }
  - { resource: form.yml }
