imports:
  - { resource: repositories.yml }
  - { resource: commands.yml }
  - { resource: cache_builder.yml }
  - { resource: events.yml }
  - { resource: factories.yml }
  - { resource: managers.yml }
  - { resource: helpers.yml }
  - { resource: console_commands.yml }
  - { resource: form.yml }
