doctrine:
    dbal:
        types: ~
    orm:
        mappings:
            module_extra:
                type: annotation
                is_bundle: false
                dir: "%kernel.project_dir%/src/Backend/Modules/Pages/Domain/ModuleExtra"
                alias: ModuleExtra
                prefix: Backend\Modules\Pages\Domain\ModuleExtra
            page_block:
                type: annotation
                is_bundle: false
                dir: "%kernel.project_dir%/src/Backend/Modules/Pages/Domain/PageBlock"
                alias: PageBlock
                prefix: Backend\Modules\Pages\Domain\PageBlock
            page:
                type: annotation
                is_bundle: false
                dir: "%kernel.project_dir%/src/Backend/Modules/Pages/Domain/Page"
                alias: Page
                prefix: Backend\Modules\Pages\Domain\Page
