services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Backend\Modules\Pages\Api\:
        resource: '../../Api/*'
    Backend\Modules\Pages\Domain\ModuleExtra\ModuleExtraRepository: ~
    Backend\Modules\Pages\Domain\PageBlock\PageBlockRepository: ~
    Backend\Modules\Pages\Domain\Page\PageRepository: ~
    Backend\Modules\Pages\Engine\CacheBuilder: ~
